// Stub for video_pll
// ---------------------------------------------------------------------------
// This is a placeholder for the vendor-provided PLL IP core.
// The actual implementation is proprietary and copyrighted by 
// PANGO MICROSYSTEMS, INC (c) 2019. Do NOT redistribute the original file.
//
// Please regenerate this module using your FPGA vendor's IP generator.
// ---------------------------------------------------------------------------

module video_pll (
    input  wire clkin1,
    input  wire pll_rst,
    output wire clkout0,
    output wire clkout1,
    output wire pll_lock
);
// Stub only: Replace with your own PLL IP generated by your FPGA platform.
endmodule
